version: "3"

services:
  verifier-app:
    ports:
      - 2804:3000
    build: .
    command: yarn start
    environment:
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_BASE_URL=https://p2804.ovpndev.2060.io
      - CREDENTIAL_DEFINITION_ID=did%3Aweb%3Achatbot-demo.dev.2060.io%3Fservice%3Danoncreds%26relativeRef%3D%2FcredDef%2FHngJhYMeTLTZNa5nJxDybmXDsV8J7G1fz2JFSs3jcouT
      - SERVICE_AGENT_ADMIN_BASE_URL=https://a.chatbot-demo.dev.2060.io
    networks:
      - verifier

networks:
  verifier:
    driver: bridge
