apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: verifier
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
---
# Public ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.name }}.{{ .Values.domain }}
      secretName: {{ .Values.name }}.{{ .Values.domain }}-cert
  rules:
    - host: {{ .Values.name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.name }}
                 port:
                   number: {{ .Values.containerPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Values.name }}
   namespace: {{ .Values.namespace }}
spec:
   serviceName: {{ .Values.name }}
   replicas: {{ .Values.replicas }}
   selector:
      matchLabels:
         app: {{ .Values.name }}
   template:
      metadata:
         labels:
            app: {{ .Values.name }}
      spec:
         containers:
         -  name: {{ .Values.name }}
            image: "{{ .Values.images.verifier.repository }}:{{ .Values.images.verifier.tag }}"
            imagePullPolicy: Always
            env:
            - name: NEXT_PUBLIC_PORT
              value: "{{ .Values.containerPort }}"
            - name: NEXT_PUBLIC_BASE_URL
              value: "https://{{ .Values.name }}.{{ .Values.domain }}"
            - name: VS_AGENT_ADMIN_BASE_URL
              value: "{{ .Values.service.agent }}"
            - name: ISSUER_DID
              value: "{{ .Values.service.issuerDid }}"
            - name: ISSUER_LABEL
              value: "{{ .Values.service.issuerLabel }}"
            - name: ISSUER_IMAGE_URL
              value: "{{ .Values.service.issuerImageUrl }}"
{{- with .Values.extraEnv }}
{{- toYaml . | nindent 12 }}
{{- end }}
            ports:
            -  containerPort: {{ .Values.containerPort }}
