apiVersion: v2
name: generic-verifier
description: A Helm chart for deploying the Generic Verifier application
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: vs-agent
    version: 1.2.1-dev.8
    repository: oci://registry-1.docker.io/io2060