apiVersion: v2
name: generic-verifier
description: A Helm chart for deploying the Generic Verifier application
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: vs-agent
    version: 142-db9daf383686ef655898b06708c538f043ba52c4
    repository: oci://registry-1.docker.io/io2060