apiVersion: v2
name: generic-verifier
description: A Helm chart for deploying the Generic Verifier application
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: vs-agent
    version: 150-9c181b78dba10dab2fd3aa7b2f8bbfec9a1430e2
    repository: oci://registry-1.docker.io/io2060