# Hologram Generic Verifier Chart Values
# This file contains the default values for the Hologram Generic Verifier Helm chart.
name: hologram-generic-verifier-vs
namespace: default
containerPort: 2904
domain: example.dev.io
replicas: 1

service:
  agent: http://verifier-agent:3000
  credentialTypes: credential-type-id
  issuerDid: did:web:unic-id-issuer.demos.dev.2060.io
  issuerLabel: test-issuer
  issuerImageUrl: https://i.unic-id-issuer.demos.dev.2060.io/avatar.png

images:
  verifier:
    repository: io2060/hologram-generic-verifier-app
    tag: v0.0.7

extraEnv: []

# If you want to use the issuer-vs chart, you can enable it by setting the following:
# vs-agent-chart.enabled: true
vs-agent-chart:
  enabled: false
  name: verifier
  namespace: default
  replicas: 1
  domain: example.dev.io
  agentName: test-verifier-agent
  eventsBaseUrl: https://verifier.example.dev.io
  database:
    enabled: false
  adminPort: 3000
  agentPort: 3001
  ingress:
    public:
      enableCors: true

  images:
    agent:
      repository: io2060/vs-agent
      tag: v1.2.1
    invitationUrl: https://i.unic-id-issuer.demos.dev.2060.io/avatar.png
    redis: 
      # Dont forget to set the redis.enabled to true if you want to use the vs-agent with a redis  
      enabled: false

  extraEnv: 
    - name: PUBLIC_API_BASE_URL
      value: https://verifier.example.dev.io
    - name: USE_CORS
      value: "true"

