name: Continuous Deployment

env:
  IMAGE_NAME: generic-verifier

on:
  push:
    branches: [ main, 'fix/create-helm-chart-on-verifier' ]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Process Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release-please.outputs) }}"

      - name: Log in to Docker Hub
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Set up Docker Buildx
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:dev,
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ steps.release-please.outputs.tag_name }}

      - name: Log in to Docker Hub Helm Registry
        run: |
          echo "$DH_TOKEN" | helm registry login -u "$DH_USERNAME" --password-stdin docker.io

      - name: Push Helm chart to Docker Hub OCI repo
        env:
          IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
        run: |
          sed -i "s/^version:.*/version: $IMAGE_TAG/" ./charts/Chart.yaml
          helm dependency update ./charts
          helm package ./charts -d ./charts
          helm push ./charts/$IMAGE_NAME-$IMAGE_TAG.tgz oci://docker.io/$DH_USERNAME
      