name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-root:
    name: Validate Root
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hologram-generic-verifier-app
        uses: actions/checkout@v4
      
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Validate Helm chart
        run: helm lint ./charts
